### ISSUE TITLE
display

### ISSUE THREAD

**Issue by GoNode5** [siegerx3/angular-tinymce#9]
When page is loading I see first a normal textarea that get replaced by tinymce. I tried a timeout but that didn't help. Is this normal behaviour?

**Comment by romion** [comment]
the same issue =(

**Comment by siegerx3** [comment]
Can you replicate the issues in a plunkr or provide me with the small project that has this issue?

**Comment by siegerx3** [comment]
I'm not sure if we can call this an issue...since the tinymce scripts are loaded dynamically, there is a small time window where the textbox is still a textbox beforre the tinymce script is loaded and initialized.

You should be able to prevent this by including the tinymce script yourself (Method 1 in the readme) instead of letting the component do it for you.

**Comment by GoNode5** [comment]
I'am already using method 1. 
If I use the https://www.tinymce.com/docs/integrations/angular2/ method I don't see this behavior. 
Thanks for your time anyway.

**Comment by siegerx3** [comment]
If there is an official solution, which i didn't know exists by now, i suggest just using this one then.

**Comment by ahinni** [comment]
It appears that adding a ```visibility: hidden``` to the generated ```textarea``` will take care of things.
